# Specify the zone for this resource
--zone:  us-west1-a

# --accelerator: 
#   type: nvidia-tesla-t4
#   count: 1

--machine-type: e2-standard-8
# autoscaling
--num-nodes: 3
--enable-autoscaling:
--min-nodes: 4
--max-nodes: 8

# # auto provisioning:
--enable-autoprovisioning: 
--max-cpu: 16
--max-memory: 64
--min-cpu: 8
--min-memory: 32
