apiVersion: v1
kind: Pod
metadata:
 name: training-pod
spec:
 restartPolicy: Never
 containers:
 - name: my-custom-container
   image: url_to_container_image
   env:
   - name: WANDB_API_KEY
     valueFrom:
       secretKeyRef:
         name: wandb-secret
         key: secret